import LocalizedStrings from 'react-native-localization';

const EN = {
  HOME: 'Home',
  PROFILE: 'Profile',
  SEARCH: 'Search',
  BY_CLICKING_LOG_IN: `By clicking "Log In" you agree with our`,
  LEARN_HOW_WE_PRCOESS: 'Learn how we process your data in our',
  TERMS: 'Terms',
  PRIVACY_POLICY: 'Privacy policy.',
  LOG_IN_WITH_PHONE_NUMBER: 'Log In with email',
  OR: 'or',
  LOG_IN_WITH_GOOGLE: 'Log In with Google',
  LOG_IN_WITH_FACEBOOK: 'Log In with Facebook',
  LOG_IN_WITH_APPLE: 'Log In with Apple',
  NEW_HERE: 'New here ? ',
  SIGN_UP: 'Sign Up',
  WELCOME_BACK: 'Welcome back!',
  WE_ARE_HAPPY_TO_SEE: 'We are happy to see. You can login to continue',
  EMAIL: 'Email',
  SAVE_NEW_PASSWORD: 'New Password',
  PLS_REGISTER_NEW_PASSWORD: 'Please enter your new password',
  UPDATE_YOUR_PROFILE_LBL: 'Update Your Profile',
  ENTER_YOUR_FULLNAME_LBL: 'Please enter your first name And last name',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm password',
  PASSWORD_ERROR: 'Your password is required!',
  CONFIRM_PASSWORD_ERROR: 'Confirm password is required!',
  CONFIRM_PASSWORD_MUST_MATCH_ERROR: 'Passwords must match!',
  SHOW: 'Show',
  HIDE: 'Hide',
  FORGOT_PASSWORD: 'Forgot Passowrd',
  USE_OTP: 'Use OTP',
  LOGIN: 'Login',
  CREATE_NEW_ACCOUNT: 'Create new account',
  CREATE_AN_ACCOUNT_SO_YOU_CAN_CONTINUE:
    'Create an account so you can continue',
  USERNAME: 'Username',
  FULL_NAME: 'Full name',
  FIRST_NAME_ERROR: 'Your first name is required!',
  LAST_NAME_ERROR: 'Your last name is required!',
  GROUP_NAME: 'Group name',
  GROUP_NAME_ERROR: 'The group name is required!',
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  MOBILE_NUMBER: 'Mobile number',
  CHOOSE_LANGUAGE: 'Choose Langauge',
  CHOOSE_THEME: 'Choose theme',
  ENTER_THE_FOUR_DIGIT: 'Enter the 4-digit code sent to you at',
  EDIT_MY_EMAIL: 'Edit my email',
  RESEND_CODE: 'Resend code',
  VERIFY: 'Verify',
  EDIT_PROFILE: 'Edit Profile',
  SAVE: 'Save',
  DONE: 'Done',
  BIO: 'Bio',
  CHANGE_PASSWORD: 'Chnage password',
  ADD_LINKS: 'Add links',
  LINKS: 'Links',
  LOGOUT: 'Logout',
  ENTER_OLD_PASSWORD: 'Enter old password',
  TITLE: 'title',
  URL: 'link',
  CREATE_POST: 'Create post',
  ADD_POST: 'Add post',
  NEXT: 'Next',
  DESCRIPTION: 'description...',
  POST_DETAIL: 'Post Detail',
  NO_COMMENT_ADDED: 'No comment added',
};

const FR = {
  HOME: 'Accueil',
  PROFILE: 'Profile',
  SEARCH: 'Rechercher',
  BY_CLICKING_LOG_IN: `En cliquant sur «Connexion», vous acceptez nos`,
  LEARN_HOW_WE_PRCOESS: 'Découvrez comment nous traitons vos données dans notre',
  TERMS: 'Termes',
  PRIVACY_POLICY: 'Politique de confidentialité.',
  LOG_IN_WITH_PHONE_NUMBER: 'Connectez-vous avec votre e-mail',
  OR: 'ou',
  LOG_IN_WITH_GOOGLE: 'Connectez-vous avec Google',
  LOG_IN_WITH_FACEBOOK: 'Se connecter avec Facebook',
  LOG_IN_WITH_APPLE: 'Connectez-vous avec Apple',
  NEW_HERE: 'Nouveau ici ?',
  SIGN_UP: 'S\'inscrire',
  WELCOME_BACK: 'Content de te revoir!',
  WE_ARE_HAPPY_TO_SEE: 'Nous sommes heureux de vous revoir. Vous pouvez vous connecter pour continuer',
  EMAIL: 'E-mail',
  SAVE_NEW_PASSWORD: 'Nouveau mot de passe',
  PLS_REGISTER_NEW_PASSWORD: 'Veuillez entrer votre nouveau mot de passe',
  UPDATE_YOUR_PROFILE_LBL: 'Mettre à jour votre profil',
  ENTER_YOUR_FULLNAME_LBL: 'Veuillez entrer votre prénom et votre nom',
  PASSWORD: 'Mot de passe',
  CONFIRM_PASSWORD: 'Confirmez le mot de passe',
  PASSWORD_ERROR: 'Votre mot de passe est requis!',
  CONFIRM_PASSWORD_ERROR: 'Confirmer le mot de passe est requis !',
  CONFIRM_PASSWORD_MUST_MATCH_ERROR: 'Les mots de passe doivent correspondre!',
  SHOW: 'Montrer',
  HIDE: 'Cacher',
  FORGOT_PASSWORD: 'Mot de passe oublié',
  USE_OTP: 'Utiliser OTP',
  LOGIN: 'Login',
  CREATE_NEW_ACCOUNT: 'Créer un nouveau compte',
  CREATE_AN_ACCOUNT_SO_YOU_CAN_CONTINUE:
    'Créez un compte pour pouvoir continuer',
  USERNAME: 'Nom d\'utilisateur',
  FULL_NAME: 'Nom et prénom',
  FIRST_NAME_ERROR: 'Votre prénom est obligatoire !',
  LAST_NAME_ERROR: 'Votre nom de famille est obligatoire!',
  GROUP_NAME: 'Nom de groupe',
  GROUP_NAME_ERROR: 'Le nom du groupe est obligatoire !',
  FIRST_NAME: 'Prénom',
  LAST_NAME: 'Nom de famille',
  MOBILE_NUMBER: 'Numéro de portable',
  CHOOSE_LANGUAGE: 'Choisissez la langue',
  CHOOSE_THEME: 'Choisissez le thème',
  ENTER_THE_FOUR_DIGIT: 'Entrez le code à 4 chiffres qui vous a été envoyé à',
  EDIT_MY_EMAIL: 'Modifier mon email',
  RESEND_CODE: 'Renvoyer le code',
  VERIFY: 'Vérifier',
  EDIT_PROFILE: 'Editer le profil',
  SAVE: 'Sauvegarder',
  DONE: 'Fait',
  BIO: 'Bio',
  CHANGE_PASSWORD: 'Changer le mot de passe',
  ADD_LINKS: 'Ajouter des liens',
  LINKS: 'Liens',
  LOGOUT: 'Se déconnecter',
  ENTER_OLD_PASSWORD: 'Entrez l\'ancien mot de passe',
  TITLE: 'titre',
  URL: 'lien',
  CREATE_POST: 'Créer une publication',
  ADD_POST: 'Ajouter une publication',
  NEXT: 'Suivant',
  DESCRIPTION: 'description...',
  POST_DETAIL: 'Détail de la publication',
  NO_COMMENT_ADDED: 'Aucun commentaire ajouté',
};

export default Strings = new LocalizedStrings({
  EN,
  FR,
});
